### PR TITLE
Metrics

### PR DESCRIPTION
**Pull request by ssanya942**
The following code contains the function to return the normalized continuous precision and recall values to validate the 5-year average benchmark and JNR. 
image
_Fig.1. Continuous Precision and Recall Formulae_

The paths of the variables '_img_dir_' (actual deforestation) and '_avg_img_dir_' (predicted deforestation) can be modified as per the requirement.

**Brief of the 5-year Average Benchmark**
The ART/TREES-inspired benchmark computes the average of deforestation taking place in a 5-year window and uses that to predict the deforestation in 3 subsequent years in the future.
image
_Fig.2. Avg 5-year benchmark diagram_

### CODE REVIEW

**Review by JackBuck — COMMENTED** [review]
Nice PR Sanya! And well scoped - it's the perfect amount of work for a PR :smile: 

I've left a few comments inline below (don't worry - I always end up commenting a lot on the first PR!). One thing I think it would be great to do is to turn this code into the start of a `metrics.py` module. This way, we can make it reusable across all of the algorithms we create. You should check the repo structure Karan suggested to see where this module would live.

One comment I would draw your attention to in particular is that I'm not convinced that the formula is implemented correctly - but it's the end of the day so perhaps I'm just tired! Probably worth addressing this one first if it is indeed a bug :bug:
https://github.com/DSSGxUK/s23_deforestation_exp/pull/5#discussion_r1261591542

**Review by na-naina — COMMENTED** [review]
Also probably shouldn't store files in main directory, make a separate experiment folder

**Review by JackBuck — COMMENTED** [review]
Thanks for the changes! I think @tarantulala also had some comments so I won't approve it yet :)

**Review by JackBuck — COMMENTED** [review]
The new version looks good Sanya! I think there are a couple of comments here which you might not have seen last time, but after that it'll be good to merge :smile:

**Review by JackBuck — APPROVED** [review]
Looks good to me - thanks Sanya!!

Since Dima reviewed before, you should get an approval from him too, but all good from my end!

**Pull request merged**
